language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn build
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
