language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
env:
- CI=true
node_js:
- '10'
before_install:
- npm config set scripts-prepend-node-path true
- npm i -g yarn
install:
- yarn
script:
  - if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ];
    then yarn release;
    else yarn test:ci;
    fi
after_success:
- yarn report-coverage
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
