language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
env:
  - CI=true
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master
      script:
        - yarn test
    - if: branch != master
      script:
        - yarn build
after_success:
  - yarn build
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
