language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
env:
  - CI=true
node_js:
  - "8"
  - "10"
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
jobs:
  include:
    - if: branch != master
      script:
        - yarn test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
